language: generic
sudo: required
services:
  - docker

before_installl:
  -docker build -e CI=true -t rahul731/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true rahul731/docker-react npm run test 