language: generic
sudo: required
services:
  - docker

before_installl:
  -docker build -t rahul731/docker-react -f Dockerfile.dev .

script:
  - docker run rahul731/docker-react npm run test -- --coverage